export { GitHubIcon } from "./github-icon";
export { Navbar } from "./navbar";
export { Hero } from "./hero";
export { Demo } from "./demo";
export { Features } from "./features";
export { HowItWorks } from "./how-it-works";
export { Privacy } from "./privacy";
export { CTA } from "./cta";
export { Footer } from "./footer";
